### ISSUE TITLE
No support for CORS

### ISSUE THREAD

**Issue by DavidZisky** [ateliedocodigo/eve-healthcheck#3]
Requests called from UI are blocked due to no CORS support. Python Eve itself sets properly CORS (when configured) but on a later stage (in settings.py definition). Looks like healtcheck module bypasses global Eve config.

**Comment by luiscoms** [comment]
Hi @DavidZisky, you can use `success_headers` and `failed_headers` of `py-healthcheck` library.

Example:

```python
cors_headers = {'Access-Control-Allow-Origin': '*'}
EveHealthCheck(success_headers=cors_headers, failed_headers=cors_headers)
```

**Comment by luiscoms** [comment]
Release [0.3.0](https://pypi.org/project/eve-healthcheck/0.3.0/) fix it
